chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('', include('Announcements.urls')),
    path('', include('course1.urls')),
    path('', include('course2.urls')),
    path('', include('course3.urls')),
    path('', include('myblog.urls')),
    path('chat/', include('chat.urls')),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.urls import reverse


# Create your models here.
User = get_user_model()

class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    posted_at = models.DateTimeField(auto_now=True, null=True)


    def __str__(self):
        return str(self.message)

    def get_absolute_url(self):
	      return reverse('chat:all')

chat/forms.py
from django import forms
from .models import Chat


class ChatForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ('message', )

chat/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from .forms import ChatForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Chat
from django.utils import timezone

# Create your views here.


class ChatCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    form_class = ChatForm
    model = Chat

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ChatListView(LoginRequiredMixin, ListView):
    model = Chat

    def get_queryset(self):
        return Chat.objects.filter(posted_at__lte=timezone.now()).order_by('posted_at')

templates/chat/chat_form.html
{% extends 'authenticate/base.html' %}

{% block content %}
    <form method="POST">
	    {% csrf_token %}
	    <center><div class="form-floating">
	    	<small>Enter Message:</small>		
		  <textarea class="form-control" placeholder="Message" name="message" style="width: 60%; height: 250px;"></textarea>
		</div></center></br>
    	<center><input type="submit" value="Send" class="btn btn btn-dark"></center>
    </form>
{% endblock content %}

templates/chat/chat_list.html
{% extends 'authenticate/base.html' %}

{% block content %}
<div>
<center><div style="border: solid 3px black; width: 90% ">
    <p align="right" style="margin-right: 10px; margin-top: 5px;"><a href="/chat"><button class="btn btn btn-dark"><i class="fa fa-refresh" aria-hidden="true"></i>
    Rerfresh</button></a></p><br>

    {% for chat in object_list %}

        <center><div class="chat" role="alert" style="width: 50%; background: rgb(192, 196, 204); border: solid 2px black; " aria-live="assertive" aria-atomic="true">
    		{% if chat.user.is_superuser %}
        		<div class="toast-header"> 
                    <strong class="me-auto">{{ chat.user }}- Admin</strong>
                    <small class="chat-date">{{ chat.posted_at }}</small> 
                </div>     
    		{% else %}
                <div class="toast-header"> 
                    <strong class="chat-user-special">{{ chat.user }}</strong>
                    <small class="chat-date">{{ chat.posted_at }}</small>
                </div>     
    		{% endif %}
            <div class="toast-body">
                {{ chat|linebreaks }}
            </div>
    	</div></center><br>

    {% empty %}
    <center><p class="heading">No Chats Yet Be The First To Message!</p><br></center>

    {% endfor %}
    <center><br><a href="{% url 'chat:new' %}"><button class="btn btn btn-dark" style="margin-bottom: 5px;">New Message</button></a></center>
</div></center>  
</div>  

{% endblock %}