chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('contactsendmail/', views.contactsendmail, name='contactsendmail')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('', include('Announcements.urls')),
    path('', include('course1.urls')),
    path('', include('course2.urls')),
    path('', include('course3.urls')),
    path('', include('myblog.urls')),
    path('chat/', include('chat.urls')),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.
class sendemail(models.Model):
	email = models.EmailField()
	subject = models.CharField(max_length=255)
	message = models.TextField()

contact/forms.py
from django import forms

class contactformemail(forms.Form):
	email = forms.EmailField(required=True)
	subject = forms.CharField(required=True)
	message = forms.CharField(widget=forms.Textarea,required=True)

contact/views.py
from django.shortcuts import render
from .forms import contactformemail
from django.core.mail import send_mail
# Create your views here.

def contactsendmail(request):
	if request.method == 'GET':
		form = contactformemail()
	else:
		form = contactformemail(request.POST)
		if form.is_valid():
			frommail=form.cleaned_data['email']
			subject=form.cleaned_data['subject']
			message=form.cleaned_data['message']
			send_mail(subject,message,frommail,['chuzair1236@gmail.com',frommail])
	return render(request, 'contact/contact.html', {'form':form})

templates/contact/contact.html
{% extends 'authenticate/base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
	<center>
		{% if perms.contact.view_sendemail %}
		<div style="width: 95%;">
		<h1>Email</h1>
		<form method="POST">
			{% csrf_token %}
		<table>
		<div class="form-group">	
		<p><label for="id_email" class="form-label">Email:</label><input type="email" class="form-control" name="email" required id="id_email" ></p>
		<p><label for="id_subject"  class="form-label">Subject:</label><input type="text" name="subject" class="form-control" required id="id_subject"></p>
		<p><label for="id_message">Message:</label><textarea class="form-control" name="message" cols="40" rows="10" required id="id_message">
		</textarea></p>
		</table> 
		</br>
		<button class="btn btn-dark">Send</button>
		</div>
		</form>
		</div>
		{% else %}
		<p>You Dont Have Access</p>
		{% endif %}
	</center>	
 {% endif %}
{% endblock %}