chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

course3/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('course3_content/',views.course3_content, name="course3_content"),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('', include('Announcements.urls')),
    path('', include('course1.urls')),
    path('', include('course2.urls')),
    path('', include('course3.urls')),
    path('', include('myblog.urls')),
    path('chat/', include('chat.urls')),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course3/models.py
from django.db import models

# Create your models here.
class file_upload(models.Model):
	ids = models.AutoField(primary_key=True)
	file_name = models.CharField(max_length=255)
	my_file = models.FileField(upload_to='')
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.file_name

course3/forms.py
from django import forms

class fileuploadform(forms.Form):
	file_name = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control'}))
	files = forms.FileField(widget = forms.FileInput(attrs={'class':'form-control'}))

course3/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import fileuploadform
from .models import file_upload
from django.contrib import messages
# Create your views here.


def course3_content(request):

	if request.method == 'POST':
		c_form = fileuploadform(request.POST, request.FILES)
		if c_form.is_valid():
			name = c_form.cleaned_data['file_name']
			file = c_form.cleaned_data['files']
			file_upload(file_name=name, my_file=file).save()
			messages.success(request, ('File Added'))
			all_data = file_upload.objects.all()
			context = {'form': fileuploadform(), 'all_data':all_data}
			return render(request, 'course3/course3_content.html',context)
		#else:
			#return render(request,'course1/course1_content.html',{})	
		else:
			all_data = file_upload.objects.all()
			context = {'form': fileuploadform(), 'all_data':all_data}
			return render(request, 'course3/course3_content.html',context)
	else:
		all_data = file_upload.objects.all()
		context = {'form': fileuploadform(), 'all_data':all_data}
		return render(request, 'course3/course3_content.html',context)

templates/course3/course3_content.html
{% extends 'authenticate/base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center">Welcome</h1>
{% if user.is_authenticated %}
	<h1 class="text-center">Course Content</h1>
	<div class="container mt-5">
		{% if perms.course2.add_file_upload %}
		<form enctype="multipart/form-data" action="{% url 'course3_content' %}" method="POST">
			{% csrf_token %}
		  <div class="mb-3">
		    <label for="{{ form.file_name.id_for_label }}" class="form-label">File Name</label>
		    {{ form.file_name }}
		  </div>
		  <div class="mb-3">
		    <label for="{{ form.files_data.id_for_label }}" class="form-label">File</label>
		    {{ form.files }}
		  </div>
		  <button type="submit" class="btn btn-secondary">Submit</button>
		</form>
		{% endif %}
	</div>
</br>
	<div class="container">
		<div class="row">
			<div class="col-12">
				<table class="table">
					<thead>
			    <tr>
			      <th>Uploaded on: </th>
			      <th>Name</th>
			      <th>Size</th>
			      <th>File Link</th>

			    </tr>
			  </thead>
			  <tbody>
			    
			    {% for d in all_data %}
			    <tr>
			      <th><cite title="Source Title">{{ d.date_added }}</cite></th>
			      <th>{{ d.file_name }}</th>
			      <th>{{ d.my_file.size }} bytes</th>
			      <th width="100px"><center><a href="{{ d.my_file.url }}"><button class="btn btn-secondary" type="submit">View/Download</button></a></center></th>
			  
			      <!-- <th><a href="{{ d.my_file.url }}"> {{ d.my_file }}</a></th> -->
			    </tr>
			    {% endfor %}
			    
			  </tbody>
			</table>
			</div>
		</div>
	</div>
 {% endif %}
{% endblock %}