authenticate/urls.py
from django.urls import path
from . import views
urlpatterns = [
    
    path('',views.home, name="home"),
    path('login/',views.login_user, name="login"),
    path('logout/',views.logout_user, name="logout"),
    path('register/',views.register_user, name="register"),
    path('profile/',views.profile, name="profile"),
    path('change_password/', views.change_password, name="change_password"),
]

chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticate.urls')),
    path('', include('Announcements.urls')),
    path('', include('course1.urls')),
    path('', include('course2.urls')),
    path('', include('course3.urls')),
    path('', include('myblog.urls')),
    path('chat/', include('chat.urls')),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticate/models.py
from django.db import models

# Create your models here.

authenticate/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User

class EditProfileForm(UserChangeForm):
	password = forms.CharField(widget=forms.TextInput(attrs={'type':'hidden'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'})) 
	last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'})) 
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password',)

	def __init__(self, *args, **kwargs):
		super(EditProfileForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].help_text = ''


class SignUpForm(UserCreationForm):
	email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
	first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'})) 
	last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'})) 

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].help_text = '<span class = "form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control' 
		self.fields['password1'].help_text = '<small><ul class = "form-text text-muted"><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric</li></ul></small>'

		self.fields['password2'].widget.attrs['class'] = 'form-control' 
		self.fields['password2'].help_text = '<span class = "form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

authenticate/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash 
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .forms import SignUpForm, EditProfileForm

# Create your views here.
def home(request):
	return render(request, 'authenticate/home.html', {})

def login_user(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password )
		if user is not None:
			login(request, user)
			messages.success(request, ('You have been Logged In!'))
			return redirect('home')
		else:
			messages.success(request, ('Wrong ID or Password'))
			return redirect('login')
	else:
		return render(request, 'authenticate/login.html', {})

def logout_user(request):
	logout(request)
	messages.success(request, ('You have been Logged Out!'))
	return redirect('login')

def register_user(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(request, username=username, password=password )
			login(request, user)
			messages.success(request, ('You have Registered'))
			return redirect('home')
	else:
		form = SignUpForm()
	context = {'form': form}		
	return render(request, 'authenticate/register.html', context)

def profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance=request.user )
		if form.is_valid():
			form.save()
			messages.success(request, ('You have Edited your Profile'))
			return redirect('home')
	else:
		form = EditProfileForm(instance=request.user)
	context = {'form': form}			
	return render(request, 'authenticate/profile.html', context)

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user )
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			messages.success(request, ('You have Edited your Password'))
			return redirect('home')
	else:
		form = PasswordChangeForm(user=request.user)
	context = {'form': form}			
	return render(request, 'authenticate/change_password.html', context)

templates/authenticate/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'CSS/bootstrap_min.css' %}" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link href="{% static 'CSS/todo_css.css' %}" rel="stylesheet">
    <link href="{% static 'CSS/style.css' %}" rel="stylesheet">

    <title>CBEL Portal</title>
  </head>
  <body>
    <style>
      .navbar-collapse {
        flex-direction: row-reverse;
      }
      #site-name > a {
        content: "adnanadfadfsdfadfa" !important;
      }
    </style>
    
  
  <div class="wrapper d-flex align-items-stretch">
      <nav id="sidebar">
        <div class="p-4 pt-5">
          <a src="{% static 'sch1.png' %}" class="img logo rounded-circle mb-5" style="background-image: url({% static 'sch1.png' %});"></a><h3 class="text-center" style="color: white" style="font-family: Segoe UI"> {{ user.first_name }} {{ user.last_name }}</h3>
          <ul class="list-unstyled components mb-5">
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'profile' %}">Profile</a>
            </li>
            <li>
                <a href="{% url 'home_todo' %}">Notice Board</a>
            </li>
            
            
            <li>
              <a href="{% url 'blog_content' %}">Blog</a>
            </li>
            <li>
              <a href="{% url 'chat:all' %}">Chat</a>
            </li>
            <li>
                <a href="{% url 'contactsendmail' %}">Email</a>
            </li>
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            
             
             {% else %}
             <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>

          

        </div>
      </nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-0">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">CBEL Online Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">

        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
  
        {% else %}
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <li class="nav-item mr-auto" >
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

      </ul>

    </div>
  </div>
        </nav>
        {% if user.is_authenticated %}
        <center>| <a href="{% url 'profile' %}" class="link">Profile</a> |
        <a href="{% url 'blog_content' %}" class="link">Blog</a> |
        <a href="{% url 'home_todo' %}" class="link">Notice Board</a> |
        <a href="{% url 'chat:all' %}" class="link">Chat</a> |
        <a href="{% url 'contactsendmail' %}" class="link">Email</a> | </center>
        <style type="text/css">
          .link {
            font-size: 20px;
            font-family: 'Poppins', sans-serif;
            color: black;
            line-height: 35px;
            transition: 250ms ease;
            opacity: 0.2;
                }
          .link:hover {
            font-size: 20px;
            font-family: 'Poppins', sans-serif;
            color: black;
            margin-left: 10px;
            margin-right: 10px;
            opacity: 1;
            text-decoration: none;
            }
        </style>
        {% endif %}
        <!-- <div class="container"> -->
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}  

     
    {% block content %}
    {% endblock %} 

    <!-- </div> -->
      

    <script src="{% static 'CSS/jquery.min.js' %}"></script>
    <script src="{% static 'CSS/popper.js' %}"></script>
    <script src="{% static 'CSS/bootstrap.min.js' %}"></script>
    <script src="{% static 'CSS/main.js' %}"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'CSS/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'CSS/chat.js' %}"> </script>


    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper 
    <script src="{% static 'CSS/bootstrap.bundle.min.js' %}" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script> -->

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
  </body>
</html> 

templates/authenticate/change_password.html
{% extends 'authenticate/base.html' %}
{% block content %}
<h1 class="text-center">Change Password</h1>
	<form method="POST" action="{% url 'change_password' %}">
		{% csrf_token %}
		{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
            	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            	<p>Your form has errors</p>
            	{% for field in form %}
            		{% if field.errors %}
            			{{ field.errors }}
            		{% endif %}
            	{% endfor %}
          	</div>
		{% endif %}
		{{ form.as_p }}
		<input type="submit" value="Change Password" class="btn btn-dark">	
	</form>

{% endblock %}

templates/authenticate/edit.html
{% extends 'authenticate/base.html' %}
{% block content %}
	{% if item %}
		</br>
		<form class="form-inline my-2 my-lg-0" method="POST">
			{% csrf_token %}
			<input class="form-control mr-sm-2" type="search" placeholder="{{ item.item }}" value="{{ item.item }}" aria-label="Search" name="item">

			<input type="hidden" value="{{ item.completed }}" name="completed">
			</br>

			<button class="btn btn-dark" type="submit">Edit</button>
		</form>
	{% endif %}		
{% endblock %}

templates/authenticate/home.html
{% extends 'authenticate/base.html' %}
{% load static %}
{% block content %}
<center><div style="width: 95%;">
<h1 class="text-center">Welcome</h1>
</br>

<!-- <p class="text-center"><small>Please <a href="{% url 'login' %}">Login</a></small></p>
</br>
<div><a img src="{% static 'logo.png' %}" alt="logo"></a></div>-->
{% if user.is_authenticated %}
	<!-- <h3 class="text-center"> {{ user.first_name }}'s Enrolled Courses</h3> 
	</br> -->
	<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'course1.png' %}" class="card-img-top" alt="my_image">
      <div class="card-body">
        <h5 class="card-title">Course 1</h5>
        <p class="card-text">Click to access content</p> 
      </div>
      <div class="card-footer">
        <div class="d-grid gap-2">
  			<a href="{% url 'course1_content' %}" class="btn btn-dark">Click Here</a>
		</div>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'course1.png' %}" class="card-img-top" alt="my_image">
      <div class="card-body">
        <h5 class="card-title">Course 2</h5>
        <p class="card-text">Click to access content</p>
      </div>
      <div class="card-footer">
       <div class="d-grid gap-2">
  			<a href="{% url 'course2_content' %}" class="btn btn-dark">Click Here</a>
		</div>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
      <img src="{% static 'course1.png' %}" class="card-img-top" alt="my_image">
      <div class="card-body">
        <h5 class="card-title">Course 3</h5>
        <p class="card-text">Click to access content</p>
      </div>
      <div class="card-footer">
        <div class="d-grid gap-2">
  			<a href="{% url 'course3_content' %}" class="btn btn-dark">Click Here</a>
		</div>
      </div>
    </div>
  </div>
</div>

 {% endif %}
</div></center>
{% endblock %}

templates/authenticate/home_todo.html
{% extends 'authenticate/base.html' %}
{% block content %}
<center><div style="width: 95%;">
{% if user.is_authenticated %}

	<h1 class="text-center">Notice Board</h1>
	{% if perms.todo %} 
		{% if perms.todo.add_list %}
			<form class="d-flex" method="POST">
				{% csrf_token %}
		
			
	        	<input class="form-control me-2" type="search" placeholder="Announcement" aria-label="Search" name="item">
	        	<button class="btn btn-dark" type="submit">Add</button>
	     	</form>
	     {% endif %}	
	 </br>
	     
	     {% if all_items %}
	     	<table class="table table-dark table-striped">
	     	{% for things in all_items %}
	     		{% if things.completed %}
	     			
			     		<tr class="table-secondary">
			     			<td  class="striker"><cite title="Source Title">{{ things.date_added }}</cite>: <h6>{{ things.item }}</h6></td>
			     			{% if perms.todo.delete_list %}
			     			<td width="100px"><center><a href="{% url 'edit' things.id %}"><button class="btn btn-secondary" type="submit">Edit</button></a></center></td>
			     			<td width="100px"><center><a href="{% url 'delete' things.id %}"><button class="btn btn-secondary" type="submit">Delete</button></a></center></td>
			     			{% endif %}
			   			</tr>
		   			
	     		{% else %}
	     			
		     			<tr>
			     			<td><cite title="Source Title">{{ things.date_added }}</cite>: <h6> {{ things.item }}</h6></td>
			     			{% if perms.todo.delete_list %}
			     			<td width="100px"><center><a href="{% url 'edit' things.id %}"><button class="btn btn-secondary" type="submit">Edit</button></a></center></td>
			     			<td width="100px"><center><a href="{% url 'delete' things.id %}"><button class="btn btn-secondary" type="submit">Delete</button></a></center></td>
			     			{% endif %}
			   			</tr>
   					
				{% endif %}		  
	     	{% endfor %}
	     	</table>	
	     {% endif %}
	    {% endif %} 
 {% endif %}
</div></center>
{% endblock %}

templates/authenticate/login.html
{% extends 'authenticate/base.html' %}
{% block content %}
<h1 class="text-center">Login</h1>
<div class="col-md-6 offset-md-3">
	<form method="POST">
		{% csrf_token %}
	  <div class="mb-3">
	    
	    <input type="text" class="form-control" placeholder="Enter username" name="username">
	  
	  </div>
	  <div class="mb-3">
	    
	    <input type="password" class="form-control" placeholder="Password" name="password">
	  </div>
	 
	  <button type="submit" class="btn btn-secondary">Login</button>
	</form>
 </div>
{% endblock %}

templates/authenticate/profile.html
{% extends 'authenticate/base.html' %}
{% block content %}
<h1 class="text-center">{{ user.first_name }} {{ user.last_name }}'s Profile</h1>
<div class="col-md-6 offset-md-3">
	<form method="POST" action="{% url 'profile' %}">
		{% csrf_token %}
		{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
            	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            	<p>Your form has errors</p>
            	{% for field in form %}
            		{% if field.errors %}
            			{{ field.errors }}
            		{% endif %}
            	{% endfor %}
          	</div>
		{% endif %}
		<!-- {{ form.as_p }} -->
		<p><label for="id_username">Username:</label> <input type="text" name="username" value="admin1" maxlength="150" class="form-control" required id="id_username" disabled></p>
		<p><label for="id_first_name">First name:</label> <input type="text" name="first_name" value="Muhammad" class="form-control" maxlength="100" required id="id_first_name"></p>
		<p><label for="id_last_name">Last name:</label> <input type="text" name="last_name" value="Uzair" class="form-control" maxlength="100" required id="id_last_name"></p>
		<p><label for="id_email">Email:</label> <input type="text" name="email" value="chuzair1236@gmail.com" class="form-control" required id="id_email"><input type="hidden" name="password" value="pbkdf2_sha256$216000$QVGTnO2Bgc3O$Q/1mO9VFiY7YftnXhXHG9HWuFeyhc6DPZq60aH1yQZU=" id="id_password"></p>
		<p class="fs-5"><small><a href="{% url 'change_password' %}">Click here</a> To change your Password</small></p>

		
		<input type="submit" value="Edit Profile" class="btn btn-dark">	
	</form>
</div>
{% endblock %}

templates/authenticate/register.html
{% extends 'authenticate/base.html' %}
{% block content %}
<h1 class="text-center">Register</h1>
<div class="col-md-6 offset-md-3">
	<form method="POST" action="{% url 'register' %}">
		{% csrf_token %}
		{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
            	<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            	<p>Your form has errors</p>
            	{% for field in form %}
            		{% if field.errors %}
            			{{ field.errors }}
            		{% endif %}
            	{% endfor %}
          	</div>
		{% endif %}
		{{ form.as_p }}
		<input type="submit" value="Register" class="btn btn-dark">	
	</form>
</div>
{% endblock %}